from __future__ import annotations

from typing import Any

from app.models import IncomingMessage


class StateStore:
    is_persistent = False

    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def record_incoming(self, msg: IncomingMessage) -> bool: ...
    async def forget_incoming(self, msg: IncomingMessage) -> None: ...
    async def load_pending_jobs(self, limit: int = 20) -> list[IncomingMessage]: ...
    async def job_status(self, message_id: str) -> str | None: ...
    async def mark_done(self, message_id: str) -> None: ...
    async def mark_failed(self, message_id: str, error: str) -> None: ...
    async def load_history(self, chat_id: str) -> list[dict[str, str]]: ...
    async def save_history(self, chat_id: str, messages: list[dict[str, str]]) -> None: ...
    async def clear_history(self, chat_id: str) -> None: ...
    async def log_message(self, dt: str, usr: str, msg: str, model_info: str = "") -> None: ...

    async def check_ready(self) -> dict[str, Any]:
        return {"ok": True}
